<?php

namespace AppBundle\Repository;

/**
 * TimestableTraitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimestableTraitRepository extends \Doctrine\ORM\EntityRepository
{
}
